name: dbt CI

on:
  pull_request:
  push:
    branches: [ "main", "master" ]

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt (BigQuery)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-bigquery==1.11.0"

      - name: Write GCP service account key
        shell: bash
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp_key.json

      - name: dbt deps
        working-directory: dbt/supply_chain_dbt
        env:
          DBT_PROFILES_DIR: .
          BQ_PROJECT_ID: ${{ secrets.BQ_PROJECT_ID }}
          BQ_DATASET: ${{ secrets.BQ_DATASET }}
          BQ_LOCATION: ${{ secrets.BQ_LOCATION }}
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_key.json
        run: |
          dbt deps

      - name: dbt build
        working-directory: dbt/supply_chain_dbt
        env:
          DBT_PROFILES_DIR: .
          BQ_PROJECT_ID: ${{ secrets.BQ_PROJECT_ID }}
          BQ_DATASET: ${{ secrets.BQ_DATASET }}
          BQ_LOCATION: ${{ secrets.BQ_LOCATION }}
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_key.json
        run: |
          dbt build --target ci
